export enum EmailTemplateKey {
    ACCOUNT_CREATED = 'ACCOUNT_CREATED',
    PASSWORD_RESET = 'PASSWORD_RESET',
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    ADMIN_PASSWORD_RESET = 'ADMIN_PASSWORD_RESET',
  }